[package]
name = "spitfire-config"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false
description = "spitfire's Lua config loader (mlua), dwm config.h-style."

[dependencies]
spitfire-layout = { path = "../spitfire-layout" }
mlua = { version = "0.12", features = ["lua54", "vendored"] }
xkbcommon = "0.8.0"
tracing = "0.1.37"
